schema_version = "1.0.0"

id = "blender_thesis_addon"
version = "1.5.0"
name = "DShot92 Thesis Addon"
tagline = "Add-on implementing Thesis algorithm to detect non manifold vertex in a clusterized mesh with differents material indices"
maintainer = "Daniele Stochino <dshot92@gmail.com>"

# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/dshot92/blender-thesis-addon"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Mesh"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"
# platforms = ["windows-x64", "linux-x64"]

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]

# Optional: required by some licenses.
copyright = ["2020-2024 Daniele Stochino"]
